version: '3.8'

services:
  nest-backend:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: development
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
